---
- name: User Create
  hosts: prod
  vars_files:
    user_list.yml
  tasks:
    - name: User task
      vars:
        password: "{{ lookup('password','filnema-'+item.name+' length=6') }}"
      ansible.builtin.user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        state: present
        password: "{{ password|password_hash('sha512') }}"
        comment: "{{ item.first|capitalize }} {{ item.middle|capitalize }} {{ item.last|capitalize }}"
      loop: "{{ users }}"
